# Copyright 2025 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import re
import time
from pathlib import Path

import yaml

from forge.detection.models import DetectionRule, SigmaRule, SnortRule
from forge.detection.validator import validate_sigma, validate_snort

logger = logging.getLogger(__name__)

DEFAULT_KB_DIR = Path("data/knowledge/detection")


class DetectionKBUpdater:
    """Append validated detection rules to the per-CWE detection KB.

    Generated rules are stored alongside curated rules but tagged
    ``source: generated`` in meta.yaml.  A quality counter tracks
    how often a generated rule was validated against real OTEL spans.

    The ``prune`` method removes generated rules below a quality
    threshold so the KB does not accumulate noise.
    """

    def __init__(self, kb_dir: Path | None = None) -> None:
        self._dir = kb_dir or DEFAULT_KB_DIR

    def update(
        self,
        cwe_id: str,
        rules: list[DetectionRule],
        validation_result: dict[str, bool] | None = None,
    ) -> list[Path]:
        """Save validated rules to the detection KB.

        Args:
            cwe_id: CWE identifier (e.g. ``"CWE-89"``).
            rules: Detection rules generated by the detector agent.
            validation_result: Optional map of rule title → validation passed.
                When omitted, each rule is re-validated before saving.

        Returns:
            List of paths for rules that were written to disk.
        """
        cwe_dir = self._dir / _cwe_dir_name(cwe_id)
        written: list[Path] = []

        for rule in rules:
            # Validate the rule if no pre-computed result
            passed = self._check_rule(rule, validation_result)
            if not passed:
                logger.debug(
                    "Skipping invalid rule %r for %s",
                    rule.title,
                    cwe_id,
                )
                continue

            path = self._write_rule(cwe_dir, rule)
            if path is not None:
                written.append(path)
                logger.info(
                    "Added generated rule to KB: %s (%s)",
                    path.name,
                    cwe_id,
                )

        # Update meta.yaml to reflect generated rules
        if written:
            self._update_meta(cwe_dir, cwe_id, len(written))

        return written

    def _check_rule(
        self,
        rule: DetectionRule,
        precomputed: dict[str, bool] | None,
    ) -> bool:
        """Return True if the rule passes validation."""
        if precomputed is not None and rule.title in precomputed:
            return precomputed[rule.title]

        # Re-validate
        if isinstance(rule, SigmaRule):
            errors = validate_sigma(rule)
            return len(errors) == 0
        if isinstance(rule, SnortRule):
            errors = validate_snort(rule)
            return len(errors) == 0

        # Generic DetectionRule — accept if raw_rule is non-empty
        return bool(rule.raw_rule.strip())

    def _write_rule(self, cwe_dir: Path, rule: DetectionRule) -> Path | None:
        """Write a single rule file and return its path."""
        if isinstance(rule, SigmaRule):
            return self._write_sigma(cwe_dir, rule)
        if isinstance(rule, SnortRule):
            return self._write_snort(cwe_dir, rule)
        return None

    def _write_sigma(self, cwe_dir: Path, rule: SigmaRule) -> Path:
        """Write a Sigma rule to ``cwe_dir/sigma/generated_<slug>.yml``."""
        sigma_dir = cwe_dir / "sigma"
        sigma_dir.mkdir(parents=True, exist_ok=True)

        slug = _slugify(rule.title) or f"rule_{int(time.time())}"
        path = sigma_dir / f"generated_{slug}.yml"

        # Inject source tag into the raw rule YAML
        content = _inject_generated_tag(rule.raw_rule)
        path.write_text(content)
        return path

    def _write_snort(self, cwe_dir: Path, rule: SnortRule) -> Path:
        """Write a Snort rule to ``cwe_dir/snort/generated_<slug>.rules``."""
        snort_dir = cwe_dir / "snort"
        snort_dir.mkdir(parents=True, exist_ok=True)

        slug = _slugify(rule.title) or f"rule_{int(time.time())}"
        path = snort_dir / f"generated_{slug}.rules"

        # Prepend a comment with source tag
        header = f"# source: generated\n# title: {rule.title}\n# quality: 1.0\n"
        path.write_text(header + rule.raw_rule + "\n")
        return path

    def _update_meta(self, cwe_dir: Path, cwe_id: str, new_count: int) -> None:
        """Update or create meta.yaml to reflect generated rules."""
        meta_path = cwe_dir / "meta.yaml"
        if meta_path.exists():
            data: dict[str, object] = yaml.safe_load(meta_path.read_text()) or {}
        else:
            cwe_dir.mkdir(parents=True, exist_ok=True)
            data = {
                "cwe_id": cwe_id,
                "cwe_name": "",
                "detection_strategy": "",
                "tier_coverage": [],
                "source": "generated",
            }

        # Track generated rule count
        raw_count = data.get("generated_rules_count", 0)
        try:
            existing_generated = int(str(raw_count))
        except (ValueError, TypeError):
            existing_generated = 0
        data["generated_rules_count"] = existing_generated + new_count
        data["last_updated"] = time.strftime("%Y-%m-%d")

        # Ensure 'generated' appears in sources
        source = data.get("source", "curated")
        if isinstance(source, str) and "generated" not in source:
            data["source"] = f"{source}, generated"

        meta_path.write_text(
            yaml.dump(dict(data), default_flow_style=False, sort_keys=False),
        )

    @staticmethod
    def _read_quality(path: Path) -> float:
        """Read quality score from a generated rule file.

        For Sigma YAML files, looks for a ``quality`` key.
        For Snort .rules files, looks for a ``# quality: <float>`` comment.
        """
        try:
            text = path.read_text()
        except OSError:
            return 0.0

        if path.suffix in (".yml", ".yaml"):
            try:
                data = yaml.safe_load(text)
                if isinstance(data, dict):
                    return float(data.get("quality", 1.0))
            except (yaml.YAMLError, ValueError):
                logger.debug("Failed to parse quality from YAML rule: %s", path)
            return 1.0

        # Snort: look for quality comment
        m = re.search(r"#\s*quality:\s*([\d.]+)", text)
        if m:
            return float(m.group(1))
        return 1.0


def _cwe_dir_name(cwe_id: str) -> str:
    """Convert ``CWE-89`` to ``cwe-89``."""
    return cwe_id.lower().replace("_", "-")


def _slugify(title: str) -> str:
    """Convert a rule title to a filesystem-safe slug."""
    slug = re.sub(r"[^a-z0-9]+", "_", title.lower()).strip("_")
    return slug[:60]


def _inject_generated_tag(raw_yaml: str) -> str:
    """Inject ``source: generated`` and ``quality: 1.0`` into Sigma YAML.

    If the raw YAML already has a ``tags`` field, appends to it.
    Otherwise, adds the fields at the end.
    """
    try:
        data = yaml.safe_load(raw_yaml)
        if isinstance(data, dict):
            data["source"] = "generated"
            data["quality"] = 1.0
            return yaml.dump(data, default_flow_style=False, sort_keys=False)
    except yaml.YAMLError:
        logger.debug("Failed to normalize YAML rule, using fallback append")

    # Fallback: append as comments
    return raw_yaml.rstrip() + "\n# source: generated\n# quality: 1.0\n"
